<?php
$url = "http://localhost/feed/";
$prefix = $url . "assets/";
?>
<html>
    <head>
        <script src="<?= $prefix ?>js/jquery-1.10.2.js"></script>
        <script src="<?= $url ?>all.js"></script>
        <script type="text/javascript">
//            $(document).ready(function () {
//                var i = 0;
////                    if (i == 1) {
////                        var src = $("#jagung_conveyor").attr("src");
////                        src = src.replace(/off/g, "on");
////                        var src1 = $("#jagung_line").attr("src");
////                        src1 = src1.replace(/off/g, "on");
////                        
////                        $("#jagung_conveyor").attr("src",src);
////                        $("#jagung_line").attr("src",src1);
////                        $("#jagung_sbm_kasar_line").attr("src","images_multi/off_jagung.png");
////                        $("#crusher").attr("src","images_multi/off_jagung_crusher.png");
////                        i = 0;
////                    } else {
////                        var src = $("#jagung_conveyor").attr("src");
////                        src = src.replace(/on/g, "off");
////                        var src1 = $("#jagung_line").attr("src");
////                        src1 = src1.replace(/on/g, "off");
////                        
////                        $("#jagung_conveyor").attr("src",src);
////                        $("#jagung_line").attr("src",src1);
////                        $("#jagung_sbm_kasar_line").attr("src","images_off/off_2_1.png");
////                        $("#crusher").attr("src","images_off/off_3_1.png");
////                        i = 1;
////                    }
//                //skenario demo jagung ong
//                var a=function(){
//                    var src = $("#jagung_conveyor").attr("src");
//                    src = src.replace(/off/g, "on");
//                    var src1 = $("#jagung_line").attr("src");
//                    src1 = src1.replace(/off/g, "on");
//
//                    $("#jagung_conveyor").attr("src", src);
//                    $("#jagung_line").attr("src", src1);
//                    $("#jagung_sbm_kasar_line").attr("src", "images_multi/off_jagung.png");
//                    $("#crusher").attr("src", "images_multi/off_jagung_crusher.png");
//                    //mengisi 10 detik
//                    setTimeout(function () {
//                        //off jagung 
//                        var src = $("#jagung_conveyor").attr("src");
//                        src = src.replace(/on/g, "off");
//                        var src1 = $("#jagung_line").attr("src");
//                        src1 = src1.replace(/on/g, "off");
//
//                        $("#jagung_conveyor").attr("src", src);
//                        $("#jagung_line").attr("src", src1);
//                        $("#jagung_sbm_kasar_line").attr("src", "images_off/off_2_1.png");
//                        $("#crusher").attr("src", "images_off/off_3_1.png");
//                        setTimeout(function () {
//                            $("#crusher").attr("src", "images_multi/off_out_jagung1_crusher.png");
//                            setTimeout(function () {
//                                $("#buffer_jagung_1").attr("src", "images_multi/jagung_1_1.png");
//                                setTimeout(function () {
//                                    $("#buffer_jagung_1").attr("src", "images_multi/jagung_1_2.png");
//                                    setTimeout(function () {
//                                        $("#buffer_jagung_1").attr("src", "images_multi/jagung_1_3.png");
//                                        setTimeout(function(){
//                                            $("#buffer_jagung_1").attr("src", "images_off/off_4_1.png");
//                                            a();
//                                        },5000);
//                                        
//                                    }, 10000);
//                                }, 10000);
//                            }, 10000);
//                        }, 5000);
//                        //out crusher
//                    }, 10000);
//                    
//                };
//                a();
//
//            });
        </script>
    </head>
    <body>
        <!--HTML SNIPPET GENERATED BY GIMP

WARNING!! This is NOT a fully valid HTML document, it is rather a piece of
HTML generated by GIMP's py-slice plugin that should be embedded in an HTML
or XHTML document to be valid.

Replace the href targets in the anchor (<a >) for your URLS to have it working
as a menu.
        -->
        <table cellpadding="0" border="0" cellspacing="0">
            <tr>
                <td><img alt=" " src="images_off/off_0_0.png" style="width: 152px;  height: 32px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_0_1.png" style="width: 148px;  height: 32px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_0_2.png" style="width: 151px;  height: 32px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_0_3.png" style="width: 148px;  height: 32px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_0_4.png" style="width: 150px;  height: 32px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_0_5.png" style="width: 150px;  height: 32px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_0_6.png" style="width: 125px;  height: 32px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " id="jagung_conveyor" src="images_off/off_1_0.png" style="width: 152px;  height: 44px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " id="sbm_kasar_conveyor" src="images_off/off_1_1.png"  style="width: 148px; height: 44px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="sbm_halus_conveyor" src="images_off/off_1_2.png"  style="width: 151px; height: 44px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="mbm_conveyor" src="images_off/off_1_3.png"  style="width: 148px; height: 44px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="katul_conveyor" src="images_off/off_1_4.png"  style="width: 150px; height: 44px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="grit_conveyor" src="images_off/off_1_5.png"  style="width: 150px; height: 44px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_1_6.png" style="width: 125px;  height: 44px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " id="jagung_line" src="images_off/off_2_0.png" style="width: 152px;  height: 30px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " id="jagung_sbm_kasar_line" src="images_off/off_2_1.png"  style="width: 148px; height: 30px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="sbm_halus_line_1" src="images_off/off_2_2.png"  style="width: 151px; height: 30px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="mbm_line_1" src="images_off/off_2_3.png"  style="width: 148px; height: 30px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="katul_line_1" src="images_off/off_2_4.png"  style="width: 150px; height: 30px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="grit_line_1" src="images_off/off_2_5.png"  style="width: 150px; height: 30px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_2_6.png" style="width: 125px;  height: 30px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_3_0.png" style="width: 152px;  height: 39px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " id="line_top_crusher" src="images_multi/off_top_crusher.png"  style="width: 148px; height: 39px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="sbm_halus_line_2" src="images_off/off_3_2.png"  style="width: 151px; height: 39px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="mbm_line_2" src="images_off/off_3_3.png"  style="width: 148px; height: 39px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="katul_line_2" src="images_off/off_3_4.png"  style="width: 150px; height: 39px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="grit_line_2" src="images_off/off_3_5.png"  style="width: 150px; height: 39px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_3_6.png" style="width: 125px;  height: 39px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_4_0.png" style="width: 152px;  height: 89px; border-width: 0px;"></td>
                <td style="background: url('images_off/off_4_1.png');width: 148px;height: 89px;border-width: 0px"><center><span id='crusher_aktif' style="text-align: center">Aktif</span></center></td>
                <td><a href="#"><img alt=" " id="sbm_halus_line_3" src="images_off/off_4_2.png"  style="width: 151px; height: 89px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="mbm_line_3" src="images_off/off_4_3.png"  style="width: 148px; height: 89px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="katul_line_3" src="images_off/off_4_4.png"  style="width: 150px; height: 89px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="grit_line_3" src="images_off/off_4_5.png"  style="width: 150px; height: 89px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_4_6.png" style="width: 125px;  height: 89px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_5_0.png" style="width: 152px;  height: 20px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " id="bottom_3" src="images_off/off_5_1.png"  style="width: 148px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="bottom_3_crusher" src="images_off/off_5_2.png"  style="width: 151px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="mbm_line_4" src="images_off/off_5_3.png"  style="width: 148px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="katul_line_4" src="images_off/off_5_4.png"  style="width: 150px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="grit_line_4" src="images_off/off_5_5.png"  style="width: 150px; height: 20px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_5_6.png" style="width: 125px;  height: 20px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_6_0.png" style="width: 152px;  height: 38px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " id="bottom_crusher" src="images_off/off_6_1.png"  style="width: 148px; height: 38px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="bottom_3_crusher_1" src="images_off/off_6_2.png"  style="width: 151px; height: 38px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="mbm_line_5" src="images_off/off_6_3.png"  style="width: 148px; height: 38px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="katul_line_5" src="images_off/off_6_4.png"  style="width: 150px; height: 38px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="grit_line_5" src="images_off/off_6_5.png"  style="width: 150px; height: 38px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_6_6.png" style="width: 125px;  height: 38px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_7_0.png" style="width: 152px;  height: 75px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " id="buffer_jagung" src="images_multi/buffer_jagung/buffer_jagung_0_jagung1_0.png"  style="width: 148px; height: 75px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="buffer_sbm" src="images_multi/buffer_sbm/sbm_0_sbm1_0.png"  style="width: 151px; height: 75px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="buffer_mbm" src="images_off/off_7_3.png"  style="width: 148px; height: 75px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="buffer_katul" src="images_off/off_7_4.png"  style="width: 150px; height: 75px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " id="buffer_grit" src="images_off/off_7_5.png"  style="width: 150px; height: 75px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_7_6.png" style="width: 125px;  height: 75px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_8_0.png" style="width: 152px;  height: 89px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_8_1.png"  style="width: 148px; height: 89px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_8_2.png"  style="width: 151px; height: 89px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_8_3.png"  style="width: 148px; height: 89px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_8_4.png"  style="width: 150px; height: 89px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_8_5.png"  style="width: 150px; height: 89px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_8_6.png" style="width: 125px;  height: 89px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_9_0.png" style="width: 152px;  height: 96px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_9_1.png"  style="width: 148px; height: 96px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_9_2.png"  style="width: 151px; height: 96px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_9_3.png"  style="width: 148px; height: 96px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_9_4.png"  style="width: 150px; height: 96px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_9_5.png"  style="width: 150px; height: 96px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_9_6.png" style="width: 125px;  height: 96px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_10_0.png" style="width: 152px;  height: 41px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_10_1.png"  style="width: 148px; height: 41px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_10_2.png"  style="width: 151px; height: 41px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_10_3.png"  style="width: 148px; height: 41px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_10_4.png"  style="width: 150px; height: 41px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_10_5.png"  style="width: 150px; height: 41px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_10_6.png" style="width: 125px;  height: 41px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_11_0.png" style="width: 152px;  height: 48px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_11_1.png"  style="width: 148px; height: 48px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_11_2.png"  style="width: 151px; height: 48px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_11_3.png"  style="width: 148px; height: 48px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_11_4.png"  style="width: 150px; height: 48px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_11_5.png"  style="width: 150px; height: 48px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_11_6.png" style="width: 125px;  height: 48px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_12_0.png" style="width: 152px;  height: 20px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_12_1.png"  style="width: 148px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_12_2.png"  style="width: 151px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_12_3.png"  style="width: 148px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_12_4.png"  style="width: 150px; height: 20px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_12_5.png"  style="width: 150px; height: 20px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_12_6.png" style="width: 125px;  height: 20px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_13_0.png" style="width: 152px;  height: 19px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_13_1.png"  style="width: 148px; height: 19px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_13_2.png"  style="width: 151px; height: 19px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_13_3.png"  style="width: 148px; height: 19px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_13_4.png"  style="width: 150px; height: 19px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_13_5.png"  style="width: 150px; height: 19px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_13_6.png" style="width: 125px;  height: 19px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_14_0.png" style="width: 152px;  height: 21px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_14_1.png"  style="width: 148px; height: 21px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_14_2.png"  style="width: 151px; height: 21px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_14_3.png"  style="width: 148px; height: 21px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_14_4.png"  style="width: 150px; height: 21px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_14_5.png"  style="width: 150px; height: 21px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_14_6.png" style="width: 125px;  height: 21px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_15_0.png" style="width: 152px;  height: 185px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_15_1.png"  style="width: 148px; height: 185px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_15_2.png"  style="width: 151px; height: 185px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_15_3.png"  style="width: 148px; height: 185px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_15_4.png"  style="width: 150px; height: 185px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_15_5.png"  style="width: 150px; height: 185px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_15_6.png" style="width: 125px;  height: 185px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_16_0.png" style="width: 152px;  height: 36px; border-width: 0px;"></td>
                <td><a href="#"><img alt=" " src="images_off/off_16_1.png"  style="width: 148px; height: 36px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_16_2.png"  style="width: 151px; height: 36px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_16_3.png"  style="width: 148px; height: 36px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_16_4.png"  style="width: 150px; height: 36px; border-width: 0px;"></a></td>
                <td><a href="#"><img alt=" " src="images_off/off_16_5.png"  style="width: 150px; height: 36px; border-width: 0px;"></a></td>
                <td><img alt=" " src="images_off/off_16_6.png" style="width: 125px;  height: 36px; border-width: 0px;"></td>
            </tr>

            <tr>
                <td><img alt=" " src="images_off/off_17_0.png" style="width: 152px;  height: 78px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_17_1.png" style="width: 148px;  height: 78px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_17_2.png" style="width: 151px;  height: 78px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_17_3.png" style="width: 148px;  height: 78px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_17_4.png" style="width: 150px;  height: 78px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_17_5.png" style="width: 150px;  height: 78px; border-width: 0px;"></td>
                <td><img alt=" " src="images_off/off_17_6.png" style="width: 125px;  height: 78px; border-width: 0px;"></td>
            </tr>

        </table>
<input type="hidden" id="jagung_conv" />
<input type="hidden" id="sbm_conv" />
<input type="hidden" id="sbm_halus"/>
<input type="hidden" id="jagung_1_buff_stat" />
<input type="hidden" id="sbm_1_buff_stat" />
    </body>
</html>


